version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    hostname: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongP@ssw0rd!"
      MSSQL_PID: "Developer"  # or use "Evaluation" if needed
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
